#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/raphael/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/raphael/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/raphael/Documents/BSS2/cortex_r1/cortex/x86_64/.libs/libnrnmech.so" "$@"
